# Generated by Django 5.0.6 on 2024-05-31 21:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_taskmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
