# Generated by Django 5.0.6 on 2024-05-31 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_taskmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
