SELECT *
FROM DEPARTMENTS
WHERE department_id=90;


SELECT FIRST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES,DEPARTMENTS
WHERE EMPLOYEES.department_id=DEPARTMENTS.department_id;


SELECT FIRST_NAME,DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS ON EMPLOYEES.department_id=DEPARTMENTS.department_id;



-- SELF JOIN :- 1.FIRST NAME AND MENEGER NAME

SELECT E.FIRST_NAME,M.FIRST_NAME
FROM EMPLOYEES AS E
	JOIN EMPLOYEES AS M
    ON E.MANAGER_ID=M.EMPLOYEE_ID;
    
    