# Generated by Django 5.0.6 on 2024-05-29 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
