# Generated by Django 5.0.6 on 2024-06-03 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_phone'),
        ('posts', '0002_alter_postsmodel_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
