# Generated by Django 5.0.6 on 2024-06-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postsmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post/media/uploads/'),
        ),
    ]
